{% set name = "vis_sample" %}
{% set version = "0.2.2" %}
{% set hash_type = "sha256" %}
{% set hash_value = "5f994728edbccf3514bb8cb4cad4b5e3e9d12e4170b7cbcc0ee0e1606253634f" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - python >=2.7.0
    - numpy >=1.13.1
    - scipy >=0.19.1
    - astropy >=1.0.0
  run:
    - python
    - python >=2.7.0
    - numpy >=1.13.1
    - scipy >=0.19.1
    - astropy >=1.0.0

test:
  imports:
    - vis_sample

about:
  home: https://github.com/AstroChem/vis_sample
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: Visibility sampler
  description: "This package fourier transforms a sky brightness image and then interpolates to arbitrary uv points\n    "
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
