# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# This package is merged into the main distribution in Python >= 3.4.

package:
  name: vis_sample
  version: "0.2.2"

source:
  fn: vis_sample-0.2.2.tar.gz
  url: https://files.pythonhosted.org/packages/ef/1f/65381d6dc19cefeeeb4888c1b4723abb06cc54d0950b9303d443023b5e64/vis_sample-0.2.2.tar.gz
  md5: 5f994728edbccf3514bb8cb4cad4b5e3e9d12e4170b7cbcc0ee0e1606253634f

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - scipy
    - astropy
  run:
    - python
    - numpy
    - scipy
    - astropy

about:
  home: https://github.com/AstroChem/vis_sample
  license: MIT License
  summary: Visibility sampler
